name: AsyncApi compiler

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  DOC_FILEPATH : src/Shared/Documentations/asyncapi.yml

jobs:
  generate_html:
    name: "Generate HTML"
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v2

      #Using another action for AsyncAPI for validation
      - name: Validating AsyncAPI document
        uses: WaleedAshraf/asyncapi-github-action@v0.0.10
        with:
          filepath: ${{ env.DOC_FILEPATH }}

      - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.1.12
        with:
          template: '@asyncapi/html-template@0.15.4'  #In case of template from npm, because of @ it must be in quotes
          filepath: ${{ env.DOC_FILEPATH }}
          parameters: baseHref=/poc-async-api/ sidebarOrganization=byTags #space separated list of key/values
          output: generated-html

      #Using another action that takes generated HTML and pushes it to GH Pages
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: generated-html
